### ISSUE TITLE
Добавить проверку

### ISSUE THREAD

**Issue by ChizhikPyzyk** [Akllike/LastNamePlayers#1]
https://github.com/Akllike/LastNamePlayers/blob/23bfb9afea5260d1a76e98d8ce2b3e6c85cc0887/addons/sourcemod/scripting/last_name.sp#L70  Добавить проверку на бота  !IsFakeClient(iClient)

**Comment by ChizhikPyzyk** [comment]
https://github.com/Akllike/LastNamePlayers/blob/23bfb9afea5260d1a76e98d8ce2b3e6c85cc0887/addons/sourcemod/scripting/last_name.sp#L45
Необходимо поправить запрос на создание таблицы. Должно быть так: **_CREATE TABLE IF NOT EXISTS last_name_**. Каждый раз при коннекте происходит попытка создать таблицу, а в логах пишет ошибку о том, что таблица существует. Поэтому нужно добавить проверку на ее существование перед тем, как попытаться ее создать.

L 01/12/2023 - 05:00:24: [last_name.smx] SQL_Callback_CheckError: Table 'last_name' already exists.

**Comment by Akllike** [comment]
> https://github.com/Akllike/LastNamePlayers/blob/23bfb9afea5260d1a76e98d8ce2b3e6c85cc0887/addons/sourcemod/scripting/last_name.sp#L45
> 
> Необходимо поправить запрос на создание таблицы. Должно быть так: **_CREATE TABLE IF NOT EXISTS last_name_**. Каждый раз при коннекте происходит попытка создать таблицу, а в логах пишет ошибку о том, что таблица существует. Поэтому нужно добавить проверку на ее существование перед тем, как попытаться ее создать.
> 
> 
> 
> L 01/12/2023 - 05:00:24: [last_name.smx] SQL_Callback_CheckError: Table 'last_name' already exists.

Принял.

**Comment by Akllike** [comment]
Исправил.

**Comment by ChizhikPyzyk** [comment]
https://github.com/Akllike/LastNamePlayers/blob/23bfb9afea5260d1a76e98d8ce2b3e6c85cc0887/addons/sourcemod/scripting/last_name.sp#L75

На этой строке гается на SQL_FetchRow. Но на 197 SQL_FetchRow тоже есть и ошибок не наблюдаю, значит проблема где-то в запросе. предположу, что здесь:
https://github.com/Akllike/LastNamePlayers/blob/23bfb9afea5260d1a76e98d8ce2b3e6c85cc0887/addons/sourcemod/scripting/last_name.sp#L77

перед `nick` должна стоять запятая, а не точка. Думаю проблема в этом.

P.S.
L 01/12/2023 - 00:25:06: [SM] Exception reported: Invalid query Handle 0 (error: 4)
L 01/12/2023 - 00:25:06: [SM] Blaming: last_name.smx
L 01/12/2023 - 00:25:06: [SM] Call stack trace:
L 01/12/2023 - 00:25:06: [SM]   [0] SQL_FetchRow
L 01/12/2023 - 00:25:06: [SM]   [1] Line 75, c:\git\main\scripting\last_name.sp::OnClientPostAdminCheck

**Comment by ChizhikPyzyk** [comment]
https://github.com/Akllike/LastNamePlayers/blob/23bfb9afea5260d1a76e98d8ce2b3e6c85cc0887/addons/sourcemod/scripting/last_name.sp#L75

На этой строке происходит ошибка:
L 01/12/2023 - 00:25:06: [SM] Exception reported: Invalid query Handle 0 (error: 4)
L 01/12/2023 - 00:25:06: [SM] Blaming: last_name.smx
L 01/12/2023 - 00:25:06: [SM] Call stack trace:
L 01/12/2023 - 00:25:06: [SM]   [0] SQL_FetchRow
L 01/12/2023 - 00:25:06: [SM]   [1] Line 75, c:\git\main\scripting\last_name.sp::OnClientPostAdminCheck

Предлагаю перед тем, как обрабатывать результат запроса, проверить его на INVALID_HANDLE

`if (query != INVALID_HANDLE)`
`{`
`   SQL_FetchRow(query)`
`   {`
`     // Делаем что-нибудь`
`   {`
`}`

SQL_Query() в случае неудачи возращает результат INVALID_HANDLE, но проверку на это мы не делаем и пихаем его сразу в SQL_FetchRow().

**Comment by Akllike** [comment]
> https://github.com/Akllike/LastNamePlayers/blob/23bfb9afea5260d1a76e98d8ce2b3e6c85cc0887/addons/sourcemod/scripting/last_name.sp#L75
> 
> На этой строке происходит ошибка: L 01/12/2023 - 00:25:06: [SM] Exception reported: Invalid query Handle 0 (error: 4) L 01/12/2023 - 00:25:06: [SM] Blaming: last_name.smx L 01/12/2023 - 00:25:06: [SM] Call stack trace: L 01/12/2023 - 00:25:06: [SM] [0] SQL_FetchRow L 01/12/2023 - 00:25:06: [SM] [1] Line 75, c:\git\main\scripting\last_name.sp::OnClientPostAdminCheck
> 
> Предлагаю перед тем, как обрабатывать результат запроса, проверить его на INVALID_HANDLE
> 
> `if (query != INVALID_HANDLE)` `{` ` SQL_FetchRow(query)` ` {` ` // Делаем что-нибудь` ` {` `}`
> 
> SQL_Query() в случае неудачи возращает результат INVALID_HANDLE, но проверку на это мы не делаем и пихаем его сразу в SQL_FetchRow().

Ты просматриваешь старую ветку, смотри новую ветку main:
https://github.com/Akllike/LastNamePlayers/blob/main/addons/sourcemod/scripting/last_name.sp#L75
